### ISSUE TITLE
Status doesn't update

### ISSUE THREAD

**Issue by rolandow** [laetificat/anna-ha#29]
I am using the development version of the home assistant plugwise integration from here: https://github.com/bouwew/anna-ha

It seems that the status is not always updating. I am aware of the delay. To replicate, you can do these steps. I don't have an active schedule by the way, I want to just control the thermostat using presets from HA.

1. Put Anna to preset "Home". I created an automation for this.
2. Change the temperature by using the slider. The display will change to " xx - Manual".
3. Put Anna to preset Home again. Now the status won't change in Home Assistant, but when I check the status in the HTML interface of smile, the data has changed.

To "fix" this, I can change the preset to "asleep", and then change it back to "home". Then I will see the right setting again.

At first I wasn't aware of the delay, I thought it might miss some preset calls, so I created an automation in HA like this:
```
anna_preset_home:
  alias: "Anna thuis"
  sequence:
    - service: climate.set_preset_mode
      data:
        entity_id: climate.Anna
        preset_mode: home
    - delay:
        seconds: 2
    - service: climate.set_preset_mode
      data:
        entity_id: climate.Anna
        preset_mode: home
```
